max_width = 120
tab_spaces = 4
use_tabs = false

edition = "2021"

merge_derives = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
format_code_in_doc_comments = true

fn_call_width = 120
fn_params_layout = "Tall"

struct_field_align_threshold = 20

chain_split_single_child = false 